#!/bin/bash
# generate-env.sh
# Generates secure .env for production
# Run: bash generate-env.sh > apps/api/.env

echo "# ── FertilityConnect India — Production ENV ──────────────"
echo "# Generated: $(date)"
echo ""
echo "NODE_ENV=production"
echo "PORT=4000"
echo ""
echo "# Database (from Neon.tech or your PostgreSQL)"
echo "DATABASE_URL=postgresql://USER:PASS@HOST:5432/fertilityconnect?sslmode=require"
echo ""
echo "# JWT Secrets (auto-generated — SAVE THESE)"
echo "JWT_SECRET=$(openssl rand -hex 32)"
echo "JWT_REFRESH_SECRET=$(openssl rand -hex 32)"
echo "JWT_EXPIRES_IN=15m"
echo "JWT_REFRESH_EXPIRES_IN=30d"
echo ""
echo "# AES-256 Encryption Key (exactly 32 chars)"
echo "ENCRYPTION_KEY=$(openssl rand -hex 16)"
echo ""
echo "OTP_EXPIRES_MINUTES=10"
echo ""
echo "# Razorpay (from dashboard.razorpay.com)"
echo "RAZORPAY_KEY_ID=rzp_live_"
echo "RAZORPAY_KEY_SECRET="
echo "RAZORPAY_WEBHOOK_SECRET=$(openssl rand -hex 24)"
echo ""
echo "# Twilio SMS"
echo "TWILIO_ACCOUNT_SID=AC"
echo "TWILIO_AUTH_TOKEN="
echo "TWILIO_PHONE=+91"
echo ""
echo "# SendGrid Email"
echo "SENDGRID_API_KEY=SG."
echo "SENDGRID_FROM_EMAIL=noreply@fertilityconnect.in"
echo "SENDGRID_FROM_NAME=FertilityConnect India"
echo ""
echo "# Frontend"
echo "FRONTEND_URL=https://fertilityconnect.in"
echo ""
echo "# Admin account (created by seed.js)"
echo "ADMIN_EMAIL=admin@fertilityconnect.in"
echo "ADMIN_PASSWORD=$(openssl rand -base64 12)!Fc1"
